#!/usr/bin/env python3
"""Prepare a Clive Context Pack for publication.

Reads one Context Pack and its linked Context Items, keeps only items that are
Status = Approved AND have Confirmed By Human set, and renders the pack to its
GitHub Path markdown file.

This script is the only part of the Publisher flow that turns approved Airtable
records into a versioned repo doc. It never writes Airtable, never runs git, and
never touches Context Item status. The human gate stays the GitHub PR plus the
approver token (which this script does not use).

Default mode is a dry run: it reports the bundle plan and writes nothing.
Pass --write to render the markdown file to disk.

Usage:
  python3 hyperagent/scripts/prepare_publish_bundle.py --pack "Clive Operating Rules"
  python3 hyperagent/scripts/prepare_publish_bundle.py --pack-id rec... --write
"""

from __future__ import annotations

import argparse
import json

from context_architecture_common import (
    REPO_ROOT,
    eq_clause,
    fail,
    list_records,
    now_iso,
)

PACK_FIELDS = [
    "Pack Name",
    "Purpose",
    "GitHub Path",
    "Version",
    "Status",
    "Context Items",
]

ITEM_FIELDS = [
    "Title",
    "Canonical Text",
    "Category",
    "Status",
    "Version",
    "Authority",
    "Confirmed By Human",
    "Source Notes",
]


def load_pack(pack_id: str | None, pack_name: str | None) -> dict:
    if pack_id:
        records = list_records(
            "Context Packs",
            fields=PACK_FIELDS,
            formula=f"RECORD_ID()='{pack_id}'",
            max_records=1,
        )
    else:
        records = list_records(
            "Context Packs",
            fields=PACK_FIELDS,
            formula=eq_clause("Pack Name", pack_name or ""),
            max_records=1,
        )
    if not records:
        fail("Context Pack not found")
    return records[0]


def load_linked_items(item_ids: list[str], max_records: int) -> list[dict]:
    if not item_ids:
        return []
    clauses = [f"RECORD_ID()='{rid}'" for rid in item_ids]
    formula = "OR(" + ",".join(clauses) + ")" if len(clauses) > 1 else clauses[0]
    return list_records(
        "Context Items",
        fields=ITEM_FIELDS,
        formula=formula,
        max_records=max_records,
    )


def split_items(items: list[dict]) -> tuple[list[dict], list[dict]]:
    included: list[dict] = []
    blocked: list[dict] = []
    for record in items:
        fields = record.get("fields", {})
        status = fields.get("Status")
        confirmed = (fields.get("Confirmed By Human") or "").strip()
        if status == "Approved" and confirmed:
            included.append(record)
        else:
            reason = []
            if status != "Approved":
                reason.append(f"Status={status or 'empty'}")
            if not confirmed:
                reason.append("Confirmed By Human empty")
            blocked.append({"record": record, "reason": "; ".join(reason)})
    return included, blocked


def render_markdown(pack_fields: dict, included: list[dict]) -> str:
    pack_name = pack_fields.get("Pack Name", "Untitled Pack")
    purpose = pack_fields.get("Purpose", "")
    version = pack_fields.get("Version", "")
    lines = [
        f"# {pack_name}",
        "",
        "> Generated by Clive Publisher from approved Context Items in AstraJax base "
        "appYv601Oq7fKTCj0.",
        f"> Pack version: {version or 'unversioned'}. Prepared: {now_iso()}.",
        "> Do not edit by hand. Edit the Context Items and re-publish.",
        "",
    ]
    if purpose:
        lines += [f"**Purpose:** {purpose}", ""]
    for record in included:
        fields = record.get("fields", {})
        title = fields.get("Title", "Untitled item")
        text = (fields.get("Canonical Text") or "").strip()
        authority = fields.get("Authority", "Unknown")
        confirmed = fields.get("Confirmed By Human", "")
        source = (fields.get("Source Notes") or "").strip()
        lines += [f"## {title}", "", text, ""]
        meta = f"_Authority: {authority} . Confirmed by: {confirmed}"
        if source:
            meta += f" . Source: {source}"
        meta += "_"
        lines += [meta, ""]
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare a Context Pack for publication")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--pack", help="Pack Name")
    group.add_argument("--pack-id", help="Context Pack record id")
    parser.add_argument("--write", action="store_true", help="Render markdown to the pack GitHub Path")
    parser.add_argument("--max-records", type=int, default=50)
    args = parser.parse_args()

    pack = load_pack(args.pack_id, args.pack)
    pack_fields = pack.get("fields", {})
    github_path = (pack_fields.get("GitHub Path") or "").strip()
    if not github_path:
        fail("Context Pack has no GitHub Path; set a destination before publishing")

    item_ids = pack_fields.get("Context Items") or []
    items = load_linked_items(item_ids, args.max_records)
    included, blocked = split_items(items)

    ready = bool(included) and not blocked
    wrote = False
    if args.write:
        if not included:
            fail("Refusing to write: no approved, human-confirmed items in this pack")
        destination = REPO_ROOT / github_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(render_markdown(pack_fields, included), encoding="utf-8")
        wrote = True

    result = {
        "success": True,
        "pack": pack_fields.get("Pack Name"),
        "pack_id": pack.get("id"),
        "destination_path": github_path,
        "linked_item_count": len(item_ids),
        "ready": ready,
        "wrote": wrote,
        "included": [
            {"id": r.get("id"), "title": r.get("fields", {}).get("Title")} for r in included
        ],
        "blocked": [
            {
                "id": b["record"].get("id"),
                "title": b["record"].get("fields", {}).get("Title"),
                "reason": b["reason"],
            }
            for b in blocked
        ],
    }
    print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
    main()
