"use client";

import Link from "next/link";
import { ExportJsonPanel } from "@/components/workshop-demo/ExportJsonPanel";
import {
  CLIVE_MAN_HANDOFF,
  DEMO_AGENT,
  IMPORT_HANDOFF,
} from "@/lib/workshop-demo/demo-data";
import { createExportReadyPaperTrail } from "@/lib/workshop-demo/paper-trail";
import type { StepNavProps } from "@/lib/workshop-demo/types";
import { useEffect } from "react";

export function ExportStep({ state, onUpdate, onBack }: StepNavProps) {
  useEffect(() => {
    if (state.paperTrail.some((line) => line.action.includes("Export ready"))) return;
    onUpdate({
      paperTrail: [...state.paperTrail, createExportReadyPaperTrail()],
    });
    // Log export-ready line once when this step mounts
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="workshop-build-demo__step space-y-6">
      <div>
        <p className="section-label text-parchment/70">Step 7 — Export and handoff</p>
        <h2 className="font-display mt-2 text-2xl font-semibold text-parchment">
          Hyperagent export
        </h2>
        <p className="mt-3 max-w-2xl text-parchment/85">
          Approved brief received. Export JSON is generated by the build script — never hand-edited.
          Matthew imports in the Hyperagent UI.
        </p>
      </div>

      <ExportJsonPanel
        downloadUrl={DEMO_AGENT.downloadUrl}
        exportFilename={DEMO_AGENT.exportFilename}
      />

      <section className="workshop-build-demo__card rounded-xl border border-parchment/15 bg-parchment/5 p-4">
        <p className="section-label text-parchment/60">Import handoff</p>
        <ul className="mt-3 list-disc space-y-1 pl-4 text-sm text-parchment/90">
          {IMPORT_HANDOFF.map((line) => (
            <li key={line}>{line}</li>
          ))}
        </ul>
      </section>

      <aside className="workshop-build-demo__handoff rounded-xl border border-sage/30 bg-sage/10 p-4">
        <p className="section-label text-parchment/70">Clive&apos;s Man handoff</p>
        <p className="mt-2 text-sm text-parchment/90">{CLIVE_MAN_HANDOFF}</p>
      </aside>

      <div className="flex flex-wrap gap-3">
        {onBack ? (
          <button type="button" className="btn-secondary" onClick={onBack}>
            Back
          </button>
        ) : null}
        <Link href="/command/doc" className="btn-secondary text-sm">
          Back to workshop
        </Link>
        <Link href="/fleet" className="btn-primary text-sm">
          Fleet design (full surface)
        </Link>
      </div>
    </div>
  );
}
