#!/usr/bin/env python3
"""Build Skill Forge Executor skill v0.1 (Hyperagent + Cursor twin).

Skill create/update via hosted MCP to Skill Forge. Auto-save stays off.
Cursor persists drafts with draft_save + resolve_approval.

Canonical skill body: .cursor/skills/skill-forge-executor/SKILL.md
One-pager (shared with Self-Update): docs/initiatives/self-update-executor-2026-08-19/how-a-change-runs.md
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _hyperagent_export import skill_data, skill_export  # noqa: E402
from _repo_paths import (  # noqa: E402
    CURSOR_SKILLS_DIR,
    EXPORTS_SKILLS_DIR,
    registry_dir,
)

SKILL_SLUG = "skill-forge-executor"
SKILL_NAME = "Skill Forge Executor"
SKILL_ICON = "⚒️"
SKILL_TAGS = '["astrajax", "skill-forge", "hyperagent", "governance", "fleet"]'
WHEN_TO_USE = (
    "When Cursor starts a Skill Forge thread with a self-contained brief to "
    "create or update a Hyperagent skill. Refuse Slack, schedule, Live, "
    "unattended, agent-identity jobs (Self-Update), and invented changes."
)
DESCRIPTION = (
    "Apply a Cursor-cleared skill create/update on Skill Forge: dump full "
    "before-state (or none — creating), apply, dump after-state. Cursor persists "
    "draft_save, verifies, restores on fail, and writes Skills / Skill Versions."
)

EXPORT_NAME = "skill-skill-forge-executor-v0_1.json"
BUILD_PACK_NAME = "build-pack-v0.1.md"


def _strip_frontmatter(text: str) -> str:
    if not text.startswith("---"):
        return text.strip()
    match = re.match(r"^---\n.*?\n---\n(.*)$", text, flags=re.DOTALL)
    return (match.group(1) if match else text).strip()


def load_skill_body() -> str:
    path = CURSOR_SKILLS_DIR / SKILL_SLUG / "SKILL.md"
    if not path.is_file():
        raise SystemExit(f"Missing Cursor skill body: {path}")
    return _strip_frontmatter(path.read_text(encoding="utf-8"))


def build_pack_markdown(*, platform: str) -> str:
    skill_body = load_skill_body()
    return """# Skill Forge Executor — Build Pack v0.1 (__PLATFORM__)

Generated by `hyperagent/builds/build_skill_forge_executor_v0_1.py`.

Shared method skill (not a new household character). Skill Forge attaches it
and applies Cursor-cleared skill briefs. Cursor twin persists `draft_save`,
verifies, restores on fail, and writes Skills / Skill Versions.

## Trinity / approval record

| Gate | Outcome |
|---|---|
| Design | Matthew directed, 19 Aug 2026 (Skill Forge twin of Self-Update) |
| Pam | **Skipped** — Matthew explicit |
| Matthew approval | Explicit build command 19 Aug 2026 |
| Risk tier | Red live writes; human gate already passed |

## Governed defaults

| Setting | Value | Note |
|---|---|---|
| All four `autoSave*` flags | **false** | Persist is Cursor `draft_save` + `resolve_approval` |
| Custom MCP | **none** | Hosted MCP only (`https://hyperagent.com/api/mcp`) |
| Skill Forge id | `cmr6im5in1iw106ad59qx2cgr` | Confirm with `list_agents` |

## Roster fit

| Axis | Decision |
|---|---|
| Decision | BUILD NEW — shared skill method, not a personality |
| Platform | Hyperagent Skill Forge (apply) + Cursor (orchestrate / persist / verify / register) |
| Channel | Interactive Cursor → hosted MCP thread on Skill Forge only |
| Trigger | Cursor Skill Forge brief |
| Scope | Skill create/update only; refuse agent identity and unattended |
| Registry | `agents/registry/__PLATFORM__/astrajax/skill-forge-executor/` |

## Artifacts

| Path | Role |
|---|---|
| `.cursor/skills/skill-forge-executor/SKILL.md` | Canonical skill body (both runtimes) |
| `.cursor/skills/skill-forge-executor/scripts/verify_skill_forge.py` | Cursor verify |
| `.cursor/skills/skill-forge-executor/scripts/hosted_mcp_handoff.py` | Hosted MCP brief + tool sequence |
| `.cursor/skills/self-update-executor/scripts/match_pending_approval.py` | Shared `draft_save` matcher |
| `hyperagent/exports/skills/__EXPORT_NAME__` | Hyperagent skill import |
| `hyperagent/scripts/sync_hyperagent_fleet_to_airtable.py` | Same register writer (`kind=skill`) |

## Skill body (embedded)

```markdown
__SKILL_BODY__
```
""".replace("__PLATFORM__", platform).replace("__EXPORT_NAME__", EXPORT_NAME).replace(
        "__SKILL_BODY__", skill_body
    )


def main() -> None:
    body = load_skill_body()
    data = skill_data(
        SKILL_NAME,
        DESCRIPTION,
        body,
        icon=SKILL_ICON,
        tags=SKILL_TAGS,
        when_to_use=WHEN_TO_USE,
        auth_type="none",
        credential_schema=None,
        skill_md_body=body,
        scripts=None,
        references=None,
    )
    export = skill_export(data)

    EXPORTS_SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    export_path = EXPORTS_SKILLS_DIR / EXPORT_NAME
    export_path.write_text(
        __import__("json").dumps(export, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    for platform in ("hyperagent", "cursor"):
        reg = registry_dir(platform, "astrajax", SKILL_SLUG)
        reg.mkdir(parents=True, exist_ok=True)
        (reg / BUILD_PACK_NAME).write_text(
            build_pack_markdown(platform=platform),
            encoding="utf-8",
        )

    print(f"Wrote {export_path}")
    print(f"Wrote registry packs under agents/registry/*/astrajax/{SKILL_SLUG}/")


if __name__ == "__main__":
    main()
