#!/usr/bin/env python3
"""Build Doc's Workshop Proposer v0.2 — Workshop Trinity design role.

Outputs registry build pack from live cursor artifacts.

Run from repo root:
  python3 hyperagent/builds/build_doc_workshop_proposer_v0_2.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _repo_paths import CURSOR_AGENTS_DIR, CURSOR_SKILLS_DIR, registry_dir  # noqa: E402


def _body_after_frontmatter(text: str) -> str:
    if text.startswith("---"):
        end = text.find("---", 3)
        return text[end + 3 :].strip() if end != -1 else text
    return text


def main() -> None:
    agent_path = CURSOR_AGENTS_DIR / "doc-workshop-proposer.md"
    skill_path = CURSOR_SKILLS_DIR / "doc-workshop-proposer" / "SKILL.md"
    if not agent_path.is_file() or not skill_path.is_file():
        raise SystemExit(f"Missing cursor artifacts: {agent_path} or {skill_path}")

    out = registry_dir("cursor", "doc", "workshop-proposer") / "build-pack-v0.2.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# Doc's Workshop Proposer v0.2 — Build Pack\n\n"
        "Generated by `hyperagent/builds/build_doc_workshop_proposer_v0_2.py`.\n\n"
        "Doc's Workshop PROPOSER. Design-only; dispatches Workshop Challenger and "
        "Composer runtime builders after Matthew approval.\n\n"
        "Supersedes `agents/registry/cursor/doc/agent-factory/` (retired naming).\n\n"
        "## System Prompt\n\n```text\n"
        + _body_after_frontmatter(agent_path.read_text(encoding="utf-8"))
        + "\n```\n\n## Skill\n\n"
        + _body_after_frontmatter(skill_path.read_text(encoding="utf-8"))
        + "\n",
        encoding="utf-8",
    )
    for path in (agent_path, skill_path, out):
        print(f"OK {path}")


if __name__ == "__main__":
    main()
