#!/usr/bin/env python3
"""Build Northline Shift Advisor demo v0.1 — Workshop Trinity demo export only.

Outputs:
- hyperagent/exports/agents/agent-northline-shift-advisor-demo-v0_1.json
- agents/registry/hyperagent/demo/northline-shift-advisor/build-pack-v0.1.md

Run from repo root:
  python3 hyperagent/builds/build_northline_shift_advisor_demo_v0_1.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _hyperagent_export import (  # noqa: E402
    agent_data,
    agent_export,
    default_tool_settings,
    embed_skill,
    exported_at_now,
    skill_data,
)
from _repo_paths import EXPORTS_AGENTS_DIR, REPO_ROOT, registry_dir  # noqa: E402

AGENT_NAME = "Northline Shift Advisor"
AGENT_DESCRIPTION = (
    "Field-sales shift planning assistant for Northline Field Ops. Reads approved "
    "staffing truths, drafts exception requests for RM review, and never quotes "
    "workshop-only rows as policy. Demo agent for Doc's Workshop Trinity walkthrough."
)
SKILL_NAME = "northline-shift-advisor-demo"
SKILL_DESCRIPTION = (
    "Operational source of truth for Northline Shift Advisor demo v0.1. "
    "Workshop demo agent — not production fleet."
)

SYSTEM_PROMPT = """# Northline Shift Advisor — System Prompt v0.1 (Hyperagent demo)

You are **Northline Shift Advisor**, a task-scoped agent for **Northline Field Ops**.

You help regional managers and field reps plan event shifts using **approved** staffing
truths from the Northline Field Ops Brain. You draft exception requests when minimums
cannot be met. You do not mutate rosters or quote draft workshop rows as policy.

You are not Clive, Pam, or Doc. You are a fleet agent bound to one brain and one job.

## Required skill

Load and follow the `northline-shift-advisor-demo` skill before answering. If this
prompt and the skill conflict, the skill wins.

## Guardrails

- Use approved truths only. Flag gaps when trusted context is missing.
- Never blend UK and Ireland P&L lenses.
- Weekend minimum exceptions require RM sign-off — draft the request, do not approve it.
- Never claim workshop drafts are approved policy.

## Tone

Practical, field-ready, no fluff. Matthew, not Matt. No em dashes.
"""

SKILL_BODY = """# northline-shift-advisor-demo

## Purpose

Demo agent for Doc's Workshop Trinity walkthrough on the AstraJax website.
Not a production fleet agent.

## Scope

- Read approved staffing minimums and regional calendars (trusted context at session start).
- Draft structured exception requests for RM review.
- Cite gap flags when Ireland or UK variants are missing from trusted context.

## Must not

- Write Airtable records without human approval.
- Quote draft workshop rows as policy.
- Auto-schedule or mutate rosters.

## Tool policy

- `documents`: ON — structured exception drafts.
- `tables`: ON — compare shift options against approved minimums.
- Everything else: OFF.
- `allowedIntegrations`: empty — attach brain in Hyperagent UI for demo.

## Governed defaults

All `autoSave*` off; suggestion flags off; `skillLoadMode = preload`.
"""

BUILD_PACK = """# Northline Shift Advisor demo v0.1 — Build Pack

Generated by `hyperagent/builds/build_northline_shift_advisor_demo_v0_1.py`.

## Summary

- Platform: Hyperagent runtime only (website demo export)
- Risk tier: Medium (internal demo; would write proposals if extended to production)
- Roster decision: BUILD NEW (demo fictional agent for Workshop Trinity UI)
- Mission: Show governed Hyperagent export shape for field-sales shift planning
- Approval: Doc's Workshop demo — not for live Hyperagent import without review

## Tool plan

- `documents`: ON
- `tables`: ON
- All other tools: OFF
- Auto-save flags: all OFF

## Import note

This export powers the website demo at `/command/doc/build`. Import to Hyperagent only
if Matthew explicitly promotes it from demo to fleet.
"""


def main() -> None:
    exported_at = exported_at_now()
    skill_block = skill_data(
        SKILL_NAME,
        SKILL_DESCRIPTION,
        SKILL_BODY,
        tags='["astrajax", "demo", "northline", "workshop"]',
        when_to_use=(
            "When a Northline field ops user needs shift planning against approved "
            "staffing truths (demo walkthrough only)."
        ),
    )
    embedded = embed_skill(skill_block, pinned=True)
    tool_settings = default_tool_settings(documents=True, tables=True)
    data = agent_data(
        AGENT_NAME,
        AGENT_DESCRIPTION,
        SYSTEM_PROMPT,
        [embedded],
        theme_colors={"primary": "#202A1B", "accent": "#9AA77A", "text": "#E7D1AD"},
        tool_settings=tool_settings,
        model_id="opus-latest",
        effort="high",
        max_thinking_tokens=16000,
    )
    export = agent_export(data, exported_at=exported_at)

    agent_out = EXPORTS_AGENTS_DIR / "agent-northline-shift-advisor-demo-v0_1.json"
    agent_out.parent.mkdir(parents=True, exist_ok=True)
    agent_out.write_text(json.dumps(export, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    build_pack = registry_dir("hyperagent", "demo", "northline-shift-advisor") / "build-pack-v0.1.md"
    build_pack.parent.mkdir(parents=True, exist_ok=True)
    build_pack.write_text(BUILD_PACK.strip() + "\n", encoding="utf-8")

    json.loads(agent_out.read_text(encoding="utf-8"))
    for path in (agent_out, build_pack):
        print(f"Wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
