#!/usr/bin/env python3
"""Build Self-Update Executor skill v0.1 (shared Hyperagent + Cursor twin).

Skill-only export: agents attach it; they stay themselves. Auto-save stays off.
Cursor persists drafts with draft_save + resolve_approval.

Outputs:
- hyperagent/exports/skills/skill-self-update-executor-v0_1.json
- agents/registry/hyperagent/astrajax/self-update-executor/build-pack-v0.1.md
- agents/registry/cursor/astrajax/self-update-executor/build-pack-v0.1.md
Canonical skill body: .cursor/skills/self-update-executor/SKILL.md
One-pager (shared with Skill Forge): docs/initiatives/self-update-executor-2026-08-19/how-a-change-runs.md
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _hyperagent_export import skill_data, skill_export  # noqa: E402
from _repo_paths import (  # noqa: E402
    CURSOR_SKILLS_DIR,
    EXPORTS_SKILLS_DIR,
    REPO_ROOT,
    registry_dir,
)

SKILL_SLUG = "self-update-executor"
SKILL_NAME = "Self-Update Executor"
SKILL_ICON = "♻️"
SKILL_TAGS = '["astrajax", "self-update", "hyperagent", "governance", "fleet"]'
WHEN_TO_USE = (
    "When Cursor starts a Self-Update thread on this agent with a self-contained "
    "brief for this agent's own config. Skill create/body change is Skill Forge. "
    "Refuse Slack, schedule, Live, unattended, other-agent updates, and invented changes."
)
DESCRIPTION = (
    "Apply a Cursor-cleared config brief to yourself only: dump full "
    "before-state, apply (draft is fine), dump full after-state. Cursor persists "
    "draft_save, verifies, restores on fail, and writes the household register. "
    "Not a personality swap. Not Skill Forge."
)

EXPORT_NAME = "skill-self-update-executor-v0_1.json"
BUILD_PACK_NAME = "build-pack-v0.1.md"
HOW_RUNS_REL = Path("docs/initiatives/self-update-executor-2026-08-19/how-a-change-runs.md")


def _strip_frontmatter(text: str) -> str:
    if not text.startswith("---"):
        return text.strip()
    match = re.match(r"^---\n.*?\n---\n(.*)$", text, flags=re.DOTALL)
    return (match.group(1) if match else text).strip()


def load_skill_body() -> str:
    path = CURSOR_SKILLS_DIR / SKILL_SLUG / "SKILL.md"
    if not path.is_file():
        raise SystemExit(f"Missing Cursor skill body: {path}")
    return _strip_frontmatter(path.read_text(encoding="utf-8"))


def build_pack_markdown(*, platform: str) -> str:
    skill_body = load_skill_body()
    return f"""# Self-Update Executor — Build Pack v0.1 ({platform})

Generated by `hyperagent/builds/build_self_update_executor_v0_1.py`.

Shared method skill (not a new household character). Hyperagent agents attach it
and apply Cursor-cleared briefs to **themselves**. Cursor twin verifies,
restores on fail, and writes the household register.

## Trinity / approval record

| Gate | Outcome |
|---|---|
| Design | Clive + Matthew, 18–19 Aug 2026 (self-update contract) |
| Pam | **Skipped** — Matthew explicit |
| Matthew approval | Explicit build command 19 Aug 2026 |
| Risk tier | Red live writes; human gate already passed |

## Governed defaults

| Setting | Value | Note |
|---|---|---|
| All four `autoSave*` flags | **false** | Governed default. Persist is Cursor `draft_save` + `resolve_approval` |
| Suggestion flags | false | |
| Custom MCP | **none** | Hosted MCP only (`https://hyperagent.com/api/mcp`) |

## Roster fit

| Axis | Decision |
|---|---|
| Decision | BUILD NEW — shared skill, not a personality |
| Platform | Hyperagent (apply) + Cursor (orchestrate / verify / register) |
| Channel | Interactive Cursor → hosted MCP thread only |
| Trigger | Cursor Self-Update brief |
| Scope | Own config/skills only; refuse other agents and unattended |
| Registry | `agents/registry/{platform}/astrajax/self-update-executor/` |

## Artifacts

| Path | Role |
|---|---|
| `.cursor/skills/self-update-executor/SKILL.md` | Canonical skill body (both runtimes) |
| `.cursor/skills/self-update-executor/scripts/verify_self_update.py` | Cursor verify (thread vs brief) |
| `.cursor/skills/self-update-executor/scripts/hosted_mcp_handoff.py` | Hosted MCP brief + tool sequence |
| `.cursor/skills/self-update-executor/scripts/match_pending_approval.py` | Shared `draft_save` matcher |
| `hyperagent/exports/skills/{EXPORT_NAME}` | Hyperagent skill import |
| `hyperagent/scripts/sync_hyperagent_fleet_to_airtable.py` | Register writer (`--verify-pass-payload`) |
| `{HOW_RUNS_REL}` | Matthew one-pager |

## Skill body (embedded)

```markdown
{skill_body}
```
""".replace("{EXPORT_NAME}", EXPORT_NAME).replace("{HOW_RUNS_REL}", str(HOW_RUNS_REL))


def how_a_change_runs() -> str:
    return """# How a change actually runs

Matthew-facing one-pager for Self-Update Executor (19 Aug 2026).

## Your part

1. Ask for the change in Cursor (same as today).
2. That is it.

No Hyperagent import per change. No Learning-queue click. No pinning skills on twelve agents. No pasting prompts into Airtable. No approve-each-apply.

## What the machines do

```text
You ask in Cursor
  → Cursor opens a Hyperagent thread on THAT agent (hosted MCP)
  → Agent dumps full BEFORE-STATE
  → Agent applies the brief (agent-config auto-save ON)
  → Agent dumps full AFTER-STATE
  → Cursor diffs after-state vs brief
  → Pass: Airtable register + repo sync
  → Fail: Cursor restores BEFORE-STATE; live register rows untouched
```

## Register writes (only after Cursor says pass)

| Table | What happens |
|---|---|
| Household Members or Minions | Live System Prompt (and related fields) updated |
| Household Versions | New snapshot row (append-only) with Change Source |
| Skills | Live skill updated if a skill changed |
| Skill Versions | New snapshot linked to the live Skills row |

Change Source defaults to **Matthew Directed** when you asked in Cursor.

## Hosted MCP (one-time)

Cursor talks to Hyperagent's **hosted** MCP. We do not host a server, and this is not the Hyperagent "Add MCP server" custom-URL path.

- **Server name in Cursor Settings:** `hyperagent`
- **Server id for Doc / tools:** `user-hyperagent`
- **URL:** `https://hyperagent.com/api/mcp`
- **Config:** `~/.cursor/mcp.json` (your Cursor user file, not in git)

**Status (19 Aug 2026):** connected. Cursor can already list your Hyperagent agents.

If it ever drops: Cursor Settings → Tools & MCP → `hyperagent` → **Connect**, then Google sign-in. Once. Revoke at https://hyperagent.com/settings/mcp-access.

## One-time bootstrap (not a per-change click)

Once: land Self-Update Executor in the Hyperagent **Skills** library (skill JSON import, or Cursor/on-platform create). After that, Cursor tells each target agent to attach the skill and turn **only** the agent-config auto-save row on. You do not pin agents by hand.

## Break-glass

If restore itself fails, stop and tell Cursor. Do not hand-edit the live agent unless you choose to.

## Paths

- Skill: `hyperagent/exports/skills/skill-self-update-executor-v0_1.json`
- Writer: `hyperagent/scripts/sync_hyperagent_fleet_to_airtable.py --verify-pass-payload …`
- Cursor verify: `.cursor/skills/self-update-executor/scripts/verify_self_update.py`
- Hosted MCP brief: `.cursor/skills/self-update-executor/scripts/hosted_mcp_handoff.py`
- Playbook: `hyperagent/docs/hyperagent-deploy-playbook.md`
"""


def main() -> None:
    body = load_skill_body()
    data = skill_data(
        SKILL_NAME,
        DESCRIPTION,
        body,
        icon=SKILL_ICON,
        tags=SKILL_TAGS,
        when_to_use=WHEN_TO_USE,
        auth_type="none",
        credential_schema=None,
        skill_md_body=body,
        scripts=None,
        references=None,
    )
    export = skill_export(data)

    EXPORTS_SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    export_path = EXPORTS_SKILLS_DIR / EXPORT_NAME
    export_path.write_text(
        __import__("json").dumps(export, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    for platform in ("hyperagent", "cursor"):
        reg = registry_dir(platform, "astrajax", SKILL_SLUG)
        reg.mkdir(parents=True, exist_ok=True)
        (reg / BUILD_PACK_NAME).write_text(
            build_pack_markdown(platform=platform),
            encoding="utf-8",
        )

    print(f"Wrote {export_path.relative_to(REPO_ROOT)}")
    print(f"Wrote registry packs under agents/registry/*/astrajax/{SKILL_SLUG}/")
    print(f"Left one-pager untouched: {HOW_RUNS_REL}")


if __name__ == "__main__":
    main()
