#!/usr/bin/env python3
"""Build Doc's Workshop Challenger v0.1 — Workshop Trinity red-team role.

Outputs:
- .cursor/agents/doc-workshop-challenger.md
- .cursor/skills/doc-workshop-challenger/SKILL.md
- agents/registry/cursor/doc/workshop-challenger/build-pack-v0.1.md

Run from repo root:
  python3 hyperagent/builds/build_doc_workshop_challenger_v0_1.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _repo_paths import CURSOR_AGENTS_DIR, CURSOR_SKILLS_DIR, registry_dir  # noqa: E402

SLUG = "doc-workshop-challenger"
REGISTRY_SLUG = "workshop-challenger"


def write_build_pack(agent_body: str, skill_body: str) -> Path:
    out = registry_dir("cursor", "doc", REGISTRY_SLUG) / "build-pack-v0.1.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# Doc's Workshop Challenger v0.1 — Build Pack\n\n"
        f"Generated by `hyperagent/builds/build_{SLUG.replace('-', '_')}_v0_1.py`.\n\n"
        "Standing Challenger in Doc's Workshop Trinity. Red-teams every Workshop "
        "config pack before Matthew sees it. Strong model; read-only.\n\n"
        "## System Prompt\n\n```text\n" + agent_body.strip() + "\n```\n\n"
        "## Skill\n\n" + skill_body.strip() + "\n",
        encoding="utf-8",
    )
    return out


def main() -> None:
    agent_path = CURSOR_AGENTS_DIR / f"{SLUG}.md"
    skill_path = CURSOR_SKILLS_DIR / SLUG / "SKILL.md"
    if not agent_path.is_file() or not skill_path.is_file():
        raise SystemExit(f"Missing cursor artifacts: {agent_path} or {skill_path}")

    agent_body = agent_path.read_text(encoding="utf-8")
    # Strip frontmatter for build pack system prompt section
    if agent_body.startswith("---"):
        end = agent_body.find("---", 3)
        agent_prompt = agent_body[end + 3 :].strip() if end != -1 else agent_body
    else:
        agent_prompt = agent_body

    skill_body = skill_path.read_text(encoding="utf-8")
    if skill_body.startswith("---"):
        end = skill_body.find("---", 3)
        skill_content = skill_body[end + 3 :].strip() if end != -1 else skill_body
    else:
        skill_content = skill_body

    pack = write_build_pack(agent_prompt, skill_content)
    for path in (agent_path, skill_path, pack):
        print(f"OK {path}")


if __name__ == "__main__":
    main()
