#!/usr/bin/env python3
"""Generate Persona Config sync artifact from Airtable (Build velocity Track 4).

Pilot: Clive's Man only (not Doc — HA/Cursor twins still diverge).

Usage:
  python3 scripts/generate_persona_config_sync.py --agent clive-man
  python3 scripts/generate_persona_config_sync.py --agent clive-man --check

Emits:
  agents/registry/cursor/clive/clive-man/persona-config.generated.md

Do not hand-edit the generated file. Change Airtable Persona Config, then re-run.
Env: AIRTABLE_READ_TOKEN or AIRTABLE_API_KEY or AIRTABLE_WRITE_TOKEN.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

AGENTS = {
    "clive-man": {
        "base": "appZ71CSKBlhnb4hR",
        "table": "tblQMlziNRMd53Yns",
        "record": "rect04amPJAZrWCi4",  # Operational v0.3 Approved
        "out": REPO
        / "agents"
        / "registry"
        / "cursor"
        / "clive"
        / "clive-man"
        / "persona-config.generated.md",
        "fields": {
            "name": "fldYeP8rAAoWtdF1s",
            "prompt": "fldpfNOynEefUJJmP",
            "rules": "fldcPAtLqfjPzt3vE",
            "output": "fldyQFbp8He2sjRAo",
            "status": "fldST2X0TjM9rba1G",
        },
    }
}

BEGIN = "<!-- BEGIN GENERATED: persona-config — do not hand-edit -->"
END = "<!-- END GENERATED: persona-config -->"


def _token() -> str:
    for key in ("AIRTABLE_READ_TOKEN", "AIRTABLE_API_KEY", "AIRTABLE_WRITE_TOKEN"):
        tok = os.environ.get(key)
        if tok:
            return tok
    env_path = REPO / ".env"
    if env_path.is_file():
        for line in env_path.read_text().splitlines():
            for key in ("AIRTABLE_READ_TOKEN", "AIRTABLE_API_KEY", "AIRTABLE_WRITE_TOKEN"):
                if line.startswith(f"{key}="):
                    return line.split("=", 1)[1].strip().strip('"').strip("'")
    raise SystemExit("Missing Airtable token in env or .env")


def _fetch(cfg: dict) -> dict:
    url = (
        f"https://api.airtable.com/v0/{cfg['base']}/{cfg['table']}/{cfg['record']}"
        f"?returnFieldsByFieldId=true"
    )
    req = urllib.request.Request(
        url, headers={"Authorization": f"Bearer {_token()}"}
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"Airtable fetch failed: {exc.code} {detail}") from exc


def _status_name(val) -> str:
    if isinstance(val, dict):
        return str(val.get("name") or "")
    return str(val or "")


def _render(cfg: dict, record: dict) -> str:
    fields = record.get("fields") or {}
    f = cfg["fields"]
    name = fields.get(f["name"]) or "(unnamed)"
    status = _status_name(fields.get(f["status"]))
    prompt = fields.get(f["prompt"]) or ""
    rules = fields.get(f["rules"]) or ""
    output = fields.get(f["output"]) or ""
    body = "\n".join(
        [
            f"# Persona Config sync — {name}",
            "",
            f"Record: `{cfg['record']}` · Status: **{status}**",
            f"Source: Airtable `{cfg['base']}` / `{cfg['table']}`",
            "",
            "Generated by `scripts/generate_persona_config_sync.py`.",
            "Edit Airtable first; re-run the script. Do not hand-edit this file.",
            "",
            BEGIN,
            "",
            "## Operational System Prompt",
            "",
            prompt.strip() or "_(empty)_",
            "",
            "## Rules Section",
            "",
            rules.strip() or "_(empty)_",
            "",
            "## Output Format",
            "",
            output.strip() or "_(empty)_",
            "",
            END,
            "",
        ]
    )
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()[:16]
    return body.replace(
        BEGIN,
        f"{BEGIN}\n<!-- content-sha256-16: {digest} -->",
        1,
    )


def generate(agent: str) -> Path:
    if agent not in AGENTS:
        raise SystemExit(f"Unknown agent {agent!r}. Pilot agents: {sorted(AGENTS)}")
    cfg = AGENTS[agent]
    record = _fetch(cfg)
    text = _render(cfg, record)
    out: Path = cfg["out"]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out.relative_to(REPO)}")
    return out


def check(agent: str) -> None:
    cfg = AGENTS[agent]
    out: Path = cfg["out"]
    if not out.is_file():
        raise SystemExit(f"Missing generated file: {out}. Run without --check first.")
    current = out.read_text(encoding="utf-8")
    record = _fetch(cfg)
    expected = _render(cfg, record)
    if current != expected:
        raise SystemExit(
            f"DRIFT: {out.relative_to(REPO)} does not match Airtable. "
            "Re-run generate (do not hand-edit the generated file)."
        )
    if BEGIN not in current or END not in current:
        raise SystemExit("Generated markers missing — file may have been hand-mangled.")
    print(f"OK no drift: {out.relative_to(REPO)}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--agent", default="clive-man")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated file drifts from Airtable",
    )
    args = parser.parse_args()
    if args.check:
        check(args.agent)
    else:
        generate(args.agent)
        check(args.agent)


if __name__ == "__main__":
    main()
